# Generated by Django 5.2.5 on 2025-08-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctor',
            unique_together={('patient', 'doctor')},
        ),
    ]
